# Generated by Django 6.1 on 2026-09-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoProfile',
            fields=[
                ('cargo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('cargo_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cargo_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cargo_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('small_box_qty', models.IntegerField(default=0)),
                ('medium_box_qty', models.IntegerField(default=0)),
                ('large_box_qty', models.IntegerField(default=0)),
                ('is_fragile', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cargo_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chat_rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_eta', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('route_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deliveries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryIssue',
            fields=[
                ('issue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delivery_issues',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pickup_type', models.CharField(max_length=50)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(default='Pending', max_length=50)),
                ('emergency_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_phone', models.CharField(max_length=50)),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'delivery_requests',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('escrow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escrow_status', models.CharField(default='On hold', max_length=50)),
                ('emergency_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bc_escrow_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'escrow_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderVerification',
            fields=[
                ('verification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('drivers_license_number', models.CharField(max_length=255, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('selfie_photo', models.CharField(max_length=255)),
                ('verification_status', models.CharField(default='Pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('bc_verif_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_id', models.BigIntegerField(blank=True, null=True)),
                ('provider_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'provider_verifications',
                'ordering': ['-submitted_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QRVerification',
            fields=[
                ('qr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pickup_qr', models.CharField(max_length=255)),
                ('dropoff_qr', models.CharField(max_length=255)),
                ('pickup_pin', models.CharField(max_length=20)),
                ('dropoff_pin', models.CharField(max_length=20)),
                ('pickup_verified', models.BooleanField(default=False)),
                ('dropoff_verified', models.BooleanField(default=False)),
                ('bc_pickup_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('bc_dropoff_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qr_verifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=50)),
                ('receiver_email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'receivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auth_id', models.UUIDField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('id_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_id_type', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_loc_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50)),
                ('max_volume_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_length_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_width_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_height_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.CharField(default='Pending', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
    ]
