# Generated by Django 6.1 on 2026-09-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'delivery_status_history',
                'ordering': ['updated_at'],
                'managed': False,
            },
        ),
    ]
